# Generated by Django 3.0.4 on 2020-04-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0002_auto_20200331_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='preaching',
            name='slug',
            field=models.SlugField(default='', editable=False),
            preserve_default=False,
        ),
    ]
