# Generated by Django 3.0.4 on 2020-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0004_remove_preaching_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='preaching',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
