# Generated by Django 3.0.4 on 2020-04-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0005_preaching_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='slug',
            field=models.SlugField(default='g', editable=False),
        ),
    ]
