# Generated by Django 3.0.4 on 2020-04-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0006_auto_20200402_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
