# Generated by Django 3.0.4 on 2020-04-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0008_auto_20200402_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
