# Generated by Django 3.0.4 on 2020-04-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0009_auto_20200402_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
