# Generated by Django 3.0.4 on 2020-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0010_auto_20200402_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('preachings', models.ManyToManyField(related_name='preachings', to='preachings.Preaching')),
            ],
        ),
    ]
