# Generated by Django 3.0.4 on 2020-04-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0011_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='preachings',
        ),
        migrations.AddField(
            model_name='preaching',
            name='tags',
            field=models.ManyToManyField(related_name='preachings', to='preachings.Tag'),
        ),
    ]
