# Generated by Django 3.0.4 on 2020-04-05 14:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0013_preaching_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
