# Generated by Django 3.0.5 on 2020-04-06 15:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0014_auto_20200405_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='preaching',
            name='text',
            field=ckeditor.fields.RichTextField(default='', max_length=3000),
        ),
    ]
