# Generated by Django 3.0.5 on 2020-04-06 15:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0015_preaching_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
