# Generated by Django 3.0.5 on 2020-04-06 15:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0016_auto_20200406_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='text',
            field=ckeditor.fields.RichTextField(default='', max_length=3000),
        ),
    ]
