# Generated by Django 3.0.5 on 2020-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0017_auto_20200406_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
