# Generated by Django 3.0.5 on 2020-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0018_auto_20200406_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='text',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
