# Generated by Django 3.0.5 on 2020-04-07 12:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0019_auto_20200406_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
