# Generated by Django 3.0.5 on 2020-04-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0020_auto_20200407_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
