# Generated by Django 3.0.5 on 2020-04-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preachings', '0021_auto_20200407_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaching',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
